// <auto-generated />
using System;
using Budget.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Budget.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251203162348_test2")]
    partial class test2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Budget.Models.MoneyTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CalculatedValue")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsThisIncome")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsThisSalary")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Money")
                        .HasColumnType("REAL");

                    b.Property<int?>("MonthId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Reocurring")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SickDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonthId");

                    b.ToTable("MoneyTransactions");
                });

            modelBuilder.Entity("Budget.Models.Month", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Months");
                });

            modelBuilder.Entity("Budget.Models.MoneyTransaction", b =>
                {
                    b.HasOne("Budget.Models.Month", null)
                        .WithMany("ListMoney")
                        .HasForeignKey("MonthId");
                });

            modelBuilder.Entity("Budget.Models.Month", b =>
                {
                    b.Navigation("ListMoney");
                });
#pragma warning restore 612, 618
        }
    }
}
